### ISSUE TITLE
Melodic climax not implemented?

### ISSUE THREAD

**Issue by paucazou** [rualark/AiHarmony#10]
In the file of rules, at the end of §32 (Melody organization), it is said that:

> Melodic climax should not be repeated in a single part.
However, I made multiple mistakes of that kind that were never detected.
In this really simple example, you can see that the C is the highest pitch and can be found twice.

[example.zip](https://github.com/rualark/AiHarmony/files/5663995/example.zip)

**Comment by rualark** [comment]
Hi. Thank you for your question. Please do not attach files, but instead send shared urls (Share - Copy).

In the rules you can see that this rule is green (allowed), except for highest part or any species 5 part.
Also, there is a green exception, which says that it is allowed in cantus firmus:

![image](https://user-images.githubusercontent.com/15198808/101606314-4bc6aa80-3a14-11eb-9a3d-2adb0ab3b1b5.png)


In your case, it is highest part, but cantus firmus (see c.f. on the left), that is why it is allowed.
If you want to set lower voice to cantus firmus, click on the part name.

**Comment by paucazou** [comment]
Yes, my example was not really good, but it's the same problem with florid counterpoint:
![Screenshot_20201211_132559](https://user-images.githubusercontent.com/25264379/101933666-ce01cb00-3bdc-11eb-8191-a283450e55aa.png)
At bar 4 and 6, you can see twice the D, which is the highest pitch.

**Comment by rualark** [comment]
Hi! Please send shared urls.

**Comment by rualark** [comment]
Thanks for reporting! Bug in multiple climax detection was fixed.

**Comment by paucazou** [comment]
Thanks !
