### ISSUE TITLE
Parallel fifths allowed on different beats?

### ISSUE THREAD

**Issue by paucazou** [rualark/AiHarmony#11]
There's something I can't understand here :
![Screenshot_20201211_182512](https://user-images.githubusercontent.com/25264379/101935063-c511f900-3bde-11eb-91fd-c0078e4c94b6.png)
See the fifths of the bar 1, 2 and 3, and also in this new screenshot :
![Screenshot_20201211_183138](https://user-images.githubusercontent.com/25264379/101935549-91839e80-3bdf-11eb-83f6-9a1279237f81.png)
Why is there a mistake in the second screenshot and not in the first one?

**Comment by rualark** [comment]
Hi! Please send shared urls (Share menu button) instead of screenshots.

**Comment by rualark** [comment]
This is allowed because beats are different in the second example (first interval is on the third beat and second interval is on the second beat). I will check this rule and update rules document if needed.

**Comment by rualark** [comment]
Yes, the algorithm was correct. I updated the rule description.
