### ISSUE TITLE
Leading tone in minor

### ISSUE THREAD

**Issue by paucazou** [rualark/AiHarmony#12]
Hello,
the rules concerning the leading tone in minor seem to be not implemented. As you can see in the example (in Cminor) I share, there are many Bb (bars 2, 4 and 8) that don't really follow the rules but no mistake is found by the program.

**Shared URL**
https://artinfuser.com/exercise/editor.html?state=IgYAwgggzAAAgDGBUhyAgaBAAoAYAFwCcBTAIwBtjE1EYAqGxAGkZgHJWBKACFoGpeiOoJgAyVm0y0AFFMQ9aAUhHjaHRJmkita1qsRtBmYbRMxuCoQARaMG.CtpSAQwDOrmABx7MAAQ-AQh9.WgB8YJ8APB8AXB9vW3s4NABlAHsABwA6NAAhNyyAIjBnADt8AFdXXyhfAEtS33z3Jl8AJl8M50J8V1awAFtWgBYAemHQkvKqgFooGYaZ5tcZtpmunpXBmeGdgAnbWhAAfQADgAlCIA

(Thank you for guidelines included in the bug report: I didn't understand how to share scores.)
(And thanks for having improved the playback feature ! It's more convenient now !)

**Comment by rualark** [comment]
Hi! Thanks for a question. By the way, I made reporting issues much easier now. Just press a Support button and shared URL will be automatically added to your report.

Bb is not a leading tong in C minor. Please see paragraph 6 of the rules:

`Leading tone is a VII chord tone in major or VII# chord tone in melodic minor, except when current chord is III and next chord is not I`

**Comment by paucazou** [comment]
Yes, that's exactly the problem : I can't understand why there's no problem using the subtonic since it's not used as a passing tone (see rule 35 B: 

> Note G (natural) can be a chord tone only inside a descending stepwise movement:
In my example, no Bb matches this defifinition.

**Comment by rualark** [comment]
This rule has no color. In this case it is disabled, because it is not important to achieve good counterpoint exercise. I should make it gray: I have to go through all the rules and check their color.

Also you can check a **table** of rules here: https://artinfuser.com/exercise/docs.php?d=cp_rules
Green background color means that rule is disabled

**Comment by paucazou** [comment]
Ok, thanks !

**Comment by rualark** [comment]
Hi! I updated most of rules descriptions, making sure that most of text has color, which shows the meaning of text in terms of the algorithm (except leap rules and some other rules).

I uploaded new rules, updated links to rules and uploaded new table of rules: https://artinfuser.com/exercise/docs.php?d=cp_rules
