### ISSUE TITLE
Contradiction against rulebook for PDD

### ISSUE THREAD

**Issue by poetslipvis** [rualark/AiHarmony#14]
https://artinfuser.com/exercise/editor.html?state=IgYAwgggzAAAgDGAIByAgaBAAEAYAFwCcBTAIwBtiYBibRGACjsQHJmYBSdgMnbfq70AJO1qI4INKQCGAZ1mI09ADhLEAXDUwAeFoD4W1fQP1d9TSq0BsQ1oAEWsxtv0AWNZeJ39G-cf77f3oHSx8tb0RfRBDEZWY4NABlAHsABwA6NAAhOXShMGkAO3wAV1k7ACY7AEtCuxTUwiLkgBpKu1TpQnxZNrA2gBYAegGAQgLisoBaCqnaqYamwuSZqc7u2SmwKYGdgBj6cRgraQAigDiAXiA_

![Schermafbeelding 2021-11-27 om 17 00 26](https://user-images.githubusercontent.com/22379041/143720644-e632eb05-1439-477d-89bf-03516be23f9c.png)
__

I do not understand how this is contradicting the rules:

![Schermafbeelding 2021-11-27 om 17 04 42](https://user-images.githubusercontent.com/22379041/143720742-84203f7b-0eca-4cac-ad5e-0913c3c44f00.png)

I even checked your own example:

https://artinfuser.com/exercise/editor.html?state=IgYAwgggzAAAgDGANhyAgaBAAoAYAFwCcBTAIwBtjE1EYByGxAKkftYAoAIWgam-dYBKVi16sANAAREcbGlIBDAM5KYAHGmIA-JpgACXRploAygHsADgDo0AIWVWAGAFkzAE2JL8egLYBLNwA7PwBzAAtvC2IFAGsAWgAGAEYADhd3T3w4.yDQiLio2MTUgBjacoBwBQAigHjyIA

![Schermafbeelding 2021-11-27 om 17 05 34](https://user-images.githubusercontent.com/22379041/143720767-bba2dec7-52b1-4dc6-a372-b7579af861e9.png)

Thanks for clarifying!

**Comment by rualark** [comment]
Hi. Yellow color in text corresponds to yellow mistake. Please read what colors mean at the beginning of the document.

Or what contradiction do you mean?

**Comment by poetslipvis** [comment]
The yellow mistake points to passing dissonance on first beat; the text says that it is allowed in species 3. So if it is allowed, it should not be seen as a mistake, correct?

**Comment by rualark** [comment]
It is allowed in yellow, please see what allowed in yellow means at the beginning of the rules document.

It means that it is not recommended, thus the warning.

It can be a little confusing, yes. But this helped to cover some complex situations in the rules.

Again, look up what colors mean in the rules.
