### ISSUE TITLE
Seems there is a bug for hidden fifths not being recognized

### ISSUE THREAD

**Issue by poetslipvis** [rualark/AiHarmony#3]
In this first species exercise, this hidden fifth seems to be unrecognized. If I'm mistaken, could you please tell me why. It sounds horrible in any case...

![Schermafbeelding 2020-11-02 om 08 31 20](https://user-images.githubusercontent.com/22379041/97863483-d285ba80-1ce5-11eb-93aa-5ff6ea9cf914.png)

To my understanding this error message should appear for bar 3

![Schermafbeelding 2020-11-02 om 08 17 52](https://user-images.githubusercontent.com/22379041/97863373-a0745880-1ce5-11eb-992d-abdfb27992cd.png)

(you should ignore the bar number in the error message example)

I do want to thank you for this MARVELOUS TOOL!!!

**Comment by poetslipvis** [comment]
Same thing here (last bar), maybe I'm missing something:

![Schermafbeelding 2020-11-02 om 08 57 20](https://user-images.githubusercontent.com/22379041/97865764-76bd3080-1ce9-11eb-8421-31e439d75cbe.png)

**Comment by rualark** [comment]
> In this first species exercise, this hidden fifth seems to be unrecognized. If I'm mistaken, could you please tell me why. It sounds horrible in any case...
> 
> ![Schermafbeelding 2020-11-02 om 08 31 20](https://user-images.githubusercontent.com/22379041/97863483-d285ba80-1ce5-11eb-93aa-5ff6ea9cf914.png)
> 
> To my understanding this error message should appear for bar 3
> 
> ![Schermafbeelding 2020-11-02 om 08 17 52](https://user-images.githubusercontent.com/22379041/97863373-a0745880-1ce5-11eb-992d-abdfb27992cd.png)
> 
> (you should ignore the bar number in the error message example)
> 
> I do want to thank you for this MARVELOUS TOOL!!!

Hi! This is considered to be the same chord (only different inversions). This is why it is allowed (see mistake name).

**Comment by rualark** [comment]
> Same thing here (last bar), maybe I'm missing something (although this sounds not too bad):
> 
> ![Schermafbeelding 2020-11-02 om 08 57 20](https://user-images.githubusercontent.com/22379041/97865764-76bd3080-1ce9-11eb-8421-31e439d75cbe.png)
> 
> It seems that similar motion to a fifth in the end is sometimes accepted actually, to mark the ending.

Looks like it is 3rd interval selected at the end, not 5th.

**Comment by poetslipvis** [comment]
> > Same thing here (last bar), maybe I'm missing something (although this sounds not too bad):
> > ![Schermafbeelding 2020-11-02 om 08 57 20](https://user-images.githubusercontent.com/22379041/97865764-76bd3080-1ce9-11eb-8421-31e439d75cbe.png)
> > It seems that similar motion to a fifth in the end is sometimes accepted actually, to mark the ending.
> 
> Looks like it is 3rd interval selected at the end, not 5th.

Of course, my bad... Many thanks, for this tool again. It's really, really great!

**Comment by poetslipvis** [comment]
> > In this first species exercise, this hidden fifth seems to be unrecognized. If I'm mistaken, could you please tell me why. It sounds horrible in any case...
> > ![Schermafbeelding 2020-11-02 om 08 31 20](https://user-images.githubusercontent.com/22379041/97863483-d285ba80-1ce5-11eb-93aa-5ff6ea9cf914.png)
> > To my understanding this error message should appear for bar 3
> > ![Schermafbeelding 2020-11-02 om 08 17 52](https://user-images.githubusercontent.com/22379041/97863373-a0745880-1ce5-11eb-992d-abdfb27992cd.png)
> > (you should ignore the bar number in the error message example)
> > I do want to thank you for this MARVELOUS TOOL!!!
> 
> Hi! This is considered to be the same chord (only different inversions). This is why it is allowed (see mistake name).

Ok, well, in this case it shouldn't be allowed, hehe... Thanks a lot for your time and attention!

**Comment by rualark** [comment]
> > > In this first species exercise, this hidden fifth seems to be unrecognized. If I'm mistaken, could you please tell me why. It sounds horrible in any case...
> > > ![Schermafbeelding 2020-11-02 om 08 31 20](https://user-images.githubusercontent.com/22379041/97863483-d285ba80-1ce5-11eb-93aa-5ff6ea9cf914.png)
> > > To my understanding this error message should appear for bar 3
> > > ![Schermafbeelding 2020-11-02 om 08 17 52](https://user-images.githubusercontent.com/22379041/97863373-a0745880-1ce5-11eb-992d-abdfb27992cd.png)
> > > (you should ignore the bar number in the error message example)
> > > I do want to thank you for this MARVELOUS TOOL!!!
> > 
> > 
> > Hi! This is considered to be the same chord (only different inversions). This is why it is allowed (see mistake name).
> 
> Ok, well, in this case it shouldn't be allowed, hehe... Thanks a lot for your time and attention!

This is not a simple question, what should be allowed and what should not. Program tries to attract attention to the things that can usually be a problem, and tries to ignore things that are usually not a problem.
