### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by poetslipvis** [rualark/AiHarmony#4]
It would be great if we could hide the mistakes until finishing the exercise and then only show the mistakes after completing the exercise.

**Comment by rualark** [comment]
Hi! Thanks for a brilliant idea! And moreover, this feature is already available. Choose No analysis here and then choose "Counterpoint" after completing the exercise:

![image](https://user-images.githubusercontent.com/15198808/97902671-f92c0b80-1d4e-11eb-8f9b-320c706825d8.png)

**Comment by poetslipvis** [comment]
This should be enough, thanks a lot! What I do think is that in Counterpoint mode, it's a little annoying when you're doing the counterpoint that it continuously gives this mistake:

![Schermafbeelding 2020-11-02 om 15 40 20](https://user-images.githubusercontent.com/22379041/97906048-c1f33580-1d21-11eb-987f-d7370aad2017.png)

While the case is that I'm simply not finished with my counterpoint, although with your solution this is also solved...

**Comment by rualark** [comment]
Yeah, this is an interesting problem. 
Still I think it is better to show some mistake like this when counterpoint is not finished yet.

**Comment by poetslipvis** [comment]
Yes, me too actually and if it annoys you then you just select No Analysis...
