### ISSUE TITLE
Notes highlighted do not correspond to the notes related to the mistake

### ISSUE THREAD

**Issue by poetslipvis** [rualark/AiHarmony#5]
I copied a Cantus Firmus that is written in C clef but that I thought was using too high notes according to the analyzer (later I realized that it was set on Sop. while I should have selected/typed in Alt). No initial problem for me, I continued the counterpoint but after seeing the mistakes I was a little confused by the following. The mistakes that are shown refer clearly to the C.F. top bar but the notes that are highlighted have little to do with it. 

![Schermafbeelding 2020-11-02 om 23 41 48](https://user-images.githubusercontent.com/22379041/97945166-6ea2d680-1d65-11eb-9bf7-6129dae29814.png)

![Schermafbeelding 2020-11-02 om 23 41 37](https://user-images.githubusercontent.com/22379041/97945233-a6118300-1d65-11eb-871a-4f27c5b593a1.png)

![Schermafbeelding 2020-11-02 om 23 41 22](https://user-images.githubusercontent.com/22379041/97945237-a90c7380-1d65-11eb-8cc3-31c41668f0a3.png)

**Comment by poetslipvis** [comment]
Ok, I've seen what the error is. It was logical but not very intuitive. I didn't realize that Artinfuser recognizes the part names. I fixed it by changing it: 

![Schermafbeelding 2020-11-02 om 23 51 19](https://user-images.githubusercontent.com/22379041/97945439-53849680-1d66-11eb-8d94-1b93a65e3f80.png)

Any idea how on making this more clear? It doesn't take away that the highlighted notes are not correct.

**Comment by poetslipvis** [comment]
I have a suggestion. Maybe when clicking on the part name one can select from standard names:

Sop.
Alt.
Ten.
Bas.

Or choose 'custom', that would make us realize that these are predefined values recognized by the system.

**Comment by rualark** [comment]
Please post shared links when you show examples (share button in menu). You can open your unsaved previous exercises in Open - Recover menu. So that you can post shared link here.

**Comment by rualark** [comment]
Also if you make screenshots it is better to make them with header, where mode is specified.

**Comment by rualark** [comment]
I will need your link to investigate this, because I could not reproduce that:
https://artinfuser.com/harmony-dev/editor.html?state=IgYAwgggzAAAgDGAwByAgaBAAoNBDAGwBcB7GAIgAREYBKaxAMgZgHIWASFgUheZvY0AxD04sRNKjRgM4uAEZ4AzkoosABCwCELKYgD4LAHgsAuCwA4xjS0M0dkljMRw0AZRIAHAHRoAQsre6gDSAKahAHbqEQCuRABOAJaRROoAxgAWePF4aUShSUpEiWkAtAAcAKxQIeERpbEJyRFEpZnZufmFxWVVUAAx0tIA-gCFAOAAT0A_

![image](https://user-images.githubusercontent.com/15198808/97959315-295fc280-1dc0-11eb-8508-cec992c48e91.png)

**Comment by poetslipvis** [comment]
I copied it manually. Ok, well, if in the future I find a new bug I will share the link. I can't reproduce it anymore, now the highlighted notes are correct.

**Comment by rualark** [comment]
Ok I will try to reproduce it later

**Comment by poetslipvis** [comment]
Another bug: https://artinfuser.com/exercise/editor.html?state=IgYAwgggzAAAgDGBshyAgaBAAoAYAFwCcBTAIwBtiYBaABEQBgZ6YmW3HnP2vXePEvRC2GDecbGlIBDAM6yYADBEAcEQGwRATBEAsDapa0AuEYB4IgPiHBysSzhoAygHsADgDo0AITkeA6AASAJYA5gAWAAQy-OGELi4AtpFuJPLUACwAnADsQWHh1DFxCYnUqcTp2TkAMWJiAPoAhQBbAOFAA__

![Schermafbeelding 2020-11-03 om 19 32 17](https://user-images.githubusercontent.com/22379041/98047816-5eddcd80-1e0b-11eb-9e1e-bff7be2e0e4a.png)

Is this the correct way you want bug reporting

**Comment by rualark** [comment]
Thanks a lot. This is the best way to report bugs (you can also include string with mode in screenshot, although it is not important in this case).

**Comment by rualark** [comment]
I updated pdf document with rules and table of rules:
https://artinfuser.com/exercise/docs.php?d=cp_rules

Now the document should be closer to real implemented rules.

Long descriptions of mistakes still need to be checked (if you choose Full mistakes text in Mistakes verbosity settings).

**Comment by rualark** [comment]
Can you please find in Open - Recover your exercise "Quirky profile jazz-932" from 2020-11-03, open it and send me the shared link?

**Comment by rualark** [comment]
I decided to remove custom part names. Now part name can be chosen only from Sop, Alt, Ten, Bas:
![image](https://user-images.githubusercontent.com/15198808/98154154-6376b480-1ee5-11eb-9226-a5f98362d5b8.png)

**Comment by poetslipvis** [comment]
> Can you please find in Open - Recover your exercise "Quirky profile jazz-932" from 2020-11-03, open it and send me the shared link?

https://artinfuser.com/exercise/editor.html?state=IgYAwgggzAAAgDGAwByAgaBAAoNBDAGwBcB7GAIgAREYBKaxAMgZgGIWASFgUheZoDkLdjV40uNEYiqI4uAEZ4AzkoosABCwCELGYgD4LAHgsAuCwA4xjS0M0dNPXDQBlEgAcAdGgBCyzwDoAIoArgCWAE4A1gCe6u4RJABmYQQApuoAVngAXjkAtACcUABMweHRMfkJyalp-dl5RaUAMTTtMAD6ACUAjgDfQA__

**Comment by poetslipvis** [comment]
> I decided to remove custom part names. Now part name can be chosen only from Sop, Alt, Ten, Bas:
> ![image](https://user-images.githubusercontent.com/15198808/98154154-6376b480-1ee5-11eb-9226-a5f98362d5b8.png)

Nice!

**Comment by rualark** [comment]
Ok, there is no problem with this example. Probably this happened as a result of some chain of actions.

**Comment by rualark** [comment]
Cannot reproduce
