### ISSUE TITLE
Another suggestion for Improvement

### ISSUE THREAD

**Issue by poetslipvis** [rualark/AiHarmony#6]
Right now selecting and dragging is a little buggy, I show in this vid:

![Schermopname 2020-11-02 om 23 59 00](https://user-images.githubusercontent.com/22379041/97945936-c04c6080-1d67-11eb-9dc3-897d0484f2e6.gif)

**Comment by rualark** [comment]
What browser and OS?

**Comment by poetslipvis** [comment]
Chrome (latest version) and Mac OS X (10.15.5)

**Comment by rualark** [comment]
This will be fixed after migration to new version of abcjs

**Comment by poetslipvis** [comment]
Seems to be fixed!
