### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by poetslipvis** [rualark/AiHarmony#7]
Hi, hope you don't mind my eagerness in submitting issues. Here these is an error message I don't understand:

![Schermafbeelding 2020-11-03 om 00 17 06](https://user-images.githubusercontent.com/22379041/97946758-13271780-1d6a-11eb-8dfb-41b4e3932271.png)

It says that the error is 'Similar motion to 5th in outer voices between chords (downbeat leap, not cadence).' 

Ok, no similar motion accepted to the 5th in outer voices, this is the case so it shows an error, fair enough. But now there is an exception (luckily, because I really liked the sound of it):

**Except** similar motion to 5th in V chord (Direct movement to 5th on downbeat with leap in upper voice: not in cadence) - from bar 6, beat 1

So in Bar 7 there is a fifth (A - E), it's the V chord (A in D major) and they are approached in direct or similar motion (G > A) and (B > E). The leap is in the upper voice (B > E) and it's not in a cadence... so it fits all the requisites but still the error message is given. Is that because it's an exception? In that case, that is a little confusing (for me). Besides, although I was happily surprised because of the exception, I couldn't find it in the Documentation... so is it or not an exception?

Maybe it can say Exception applied! (in green so it stands out, because if it's all in red you read over it) - Harmony: and then still include the full error message so we learn that in general it's an error and something to be careful of.

**Comment by rualark** [comment]
Yeah, long descriptions of mistakes can be a little dated. I have to go through them and check.
If you find some other, please post.

**Comment by poetslipvis** [comment]
So the first error message got me confused because I don't know wether I'm doing something good. In the error message it says that my case is accepted as an exception but in the documentation I can't find it. 

But now I have the case where actually I'm wondering where the error message is. I'm using a diminished interval (III > #VII > I) and I was thinking, shouldn't this be wrong? So I looked up the documentation and I see the exception. I think the error should appear but in a green color, when the for exception is applied, this would be very instructive. 

_(Still wondering wether it is true if similar motion to 5th in V chord (Direct movement to 5th on downbeat with leap in upper voice: not in cadence is an acceptable (the first example).)_

**Comment by rualark** [comment]
Currently green colored text in docs represents situations when no mistake is shown. Only orange and green mistakes are shown to prevent cluttering.

To discuss particular example please provide a shared link

**Comment by rualark** [comment]
I synchronized rule description with document. Exception is:
Except similar motion between I64 and V chord

I will be able to test if you provide shared link :)

**Comment by poetslipvis** [comment]
I've already seen it appearing, it works! Can't find the link, sorry
